channel_targets:
- conda-forge mpi-external # [linux]
- conda-forge main

mpi_type:
  - external  # [linux]
  - conda
libfabric:
  - "1.19"
libpmix_devel:
  - "6"

zip_keys:
  -
    - mpi_type
    - channel_targets
