# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic



matrix:
  include:
    - env: CONFIG=linux_aarch64_c_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11fortran_compiler_version11mpi_typeconda UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64-cuda:11.8
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_c_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11fortran_compiler_version11mpi_typeexternal UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64-cuda:11.8
      os: linux
      arch: arm64
      dist: focal

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"
  - export flow_run_id="travis_$TRAVIS_JOB_ID"
  - export sha="$TRAVIS_COMMIT"
  - export remote_url="https://github.com/$TRAVIS_REPO_SLUG"
  - export FEEDSTOCK_NAME=$(basename ${TRAVIS_REPO_SLUG})
  - if [[ "${TRAVIS_PULL_REQUEST:-}" == "false" ]]; then export IS_PR_BUILD="False"; else export IS_PR_BUILD="True"; fi


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then CONDA_FORGE_DOCKER_RUN_ARGS="--network=host --security-opt=seccomp=unconfined" ./.scripts/run_docker_build.sh; fi